import { readFileSync } from "node:fs";
import { describe, expect, test } from "vitest";

describe("hosted playtest copy", () => {
  test("keeps account and sync-facing notices in Chinese", () => {
    const source = [
      "src/App.tsx",
      "src/lib/auth.ts",
      "src/lib/remoteState.ts",
      "functions/api/auth/register.js"
    ]
      .map((path) => readFileSync(path, "utf8"))
      .join("\n");

    expect(source).toContain("邮箱已确认，正在读取你的试玩账号。");
    expect(source).toContain("账号需要 3-20 位小写字母、数字或下划线。");
    expect(source).not.toMatch(
      /Email confirmed|Loading your playtest account|Username must be|Password needs|Registration failed|Continue as guest|Supabase did not return a session|Username signup did not return a session|Supabase request failed with HTTP/
    );
  });

  test("shows a Chinese expedition launch checklist in the prep UI", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("expeditionLaunchChecklist");
    expect(source).toContain("aria-label=\"出征检查\"");
    expect(source).toContain("aria-label=\"出征开局预案\"");
    expect(source).toContain("aria-label=\"出发决策摘要\"");
    expect(source).toContain("aria-label=\"本次远征收益预览\"");
    expect(source).toContain("expeditionYieldPreview");
    expect(source).toContain("departureDecisionItems");
    expect(source).toContain("出发判断");
    expect(source).toContain("路线压力");
    expect(source).toContain("补给容错");
    expect(source).toContain("预期收益");
    expect(source).toContain("收益预览");
    expect(source).toContain("yield-preview");
    expect(source).toContain("departure-decision-card");
    expect(source).toContain("dispatch-briefing");
    expect(source).toContain("出征检查");
    expect(styles).toContain(".departure-decision-card");
    expect(styles).toContain(".departure-decision-grid");
    expect(styles).toContain(".dispatch-briefing");
    expect(styles).toContain(".yield-preview");
  });

  test("shows survivor growth planning as a base loop surface", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("survivorGrowthPlan");
    expect(source).toContain("survivorExpeditionGrowthPreview");
    expect(source).toContain("expeditionXpGain");
    expect(source).toContain("survivorRoleBoard");
    expect(source).toContain("baseShiftPlan");
    expect(source).toContain("shiftPlan={baseShiftPlan(session)}");
    expect(source).toContain("aria-label=\"幸存者培养队列\"");
    expect(source).toContain("aria-label=\"出征成长预期\"");
    expect(source).toContain("aria-label=\"幸存者定位建议\"");
    expect(source).toContain("accountGrowthBoundary");
    expect(source).toContain("aria-label=\"账号成长边界\"");
    expect(source).toContain("growthBoundary.survivorProgressLabel");
    expect(source).toContain("growthBoundary.baseCapLabel");
    expect(source).toContain("培养队列");
    expect(source).toContain("编队定位");
    expect(source).toContain("出征核心");
    expect(source).toContain("医疗护理");
    expect(source).toContain("修理建设");
    expect(source).toContain("守卫防线");
    expect(source).toContain("按顺序处理，下一次出征更稳。");
    expect(source).toContain("标准完整撤离预计");
    expect(styles).toContain(".base-shift-plan");
    expect(styles).toContain(".base-shift-plan-grid");
    expect(styles).toContain(".base-shift-plan-grid article.urgent");
    expect(styles).toContain(".account-growth-boundary");
    expect(styles).toContain(".account-growth-metrics");
    expect(styles).toContain(".growth-plan-card");
    expect(styles).toContain(".growth-plan-grid");
    expect(styles).toContain(".growth-plan-item.ready");
    expect(styles).toContain(".growth-plan-item.blocked");
    expect(styles).toContain(".expedition-growth-preview");
    expect(styles).toContain(".expedition-growth-grid article.ready");
    expect(styles).toContain(".expedition-growth-grid article.capped");
    expect(styles).toContain(".survivor-role-board");
    expect(styles).toContain(".survivor-role-grid");
    expect(styles).toContain(".survivor-role-item.ready");
    expect(styles).toContain(".survivor-role-item.urgent");
  });

  test("keeps expedition prep as a mobile-first single-page command flow", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("aria-label=\"出征准备指挥台\"");
    expect(source).toContain("aria-label=\"出征准备步骤\"");
    expect(source).toContain("expedition-prep-command");
    expect(source).toContain("expedition-prep-steps");
    expect(source).toContain("scrollToPrepStep");
    expect(source).toContain("document.getElementById(id)?.scrollIntoView");
    expect(source).toContain("id=\"prep-squad\"");
    expect(source).toContain("id=\"prep-route\"");
    expect(source).toContain("aria-label=\"出征地点列表\"");
    expect(source).toContain("location-choice-grid");
    expect(source).toContain("location-choice-card");
    expect(source).toContain("locationRewardSummary");
    expect(source).toContain("主要收益");
    expect(source).toContain("location.recommendedStats.map");
    expect(source).toContain("location.tags.slice(0, 3)");
    expect(source).toContain("id=\"prep-loadout\"");
    expect(source).toContain("id=\"prep-risk\"");
    expect(styles).toContain(".expedition-prep-command");
    expect(styles).toContain(".expedition-prep-step");
    expect(styles).toContain(".location-choice-grid");
    expect(styles).toContain(".location-choice-card");
    expect(styles).toContain(".location-choice-reward");
    expect(styles).toContain(".location-choice-stats");
    expect(styles).toContain(".location-choice-tags");
    expect(styles).toContain("scroll-margin-top");
  });

  test("shows a Chinese action guide during expeditions", () => {
    const source = readFileSync("src/App.tsx", "utf8");

    expect(source).toContain("journeyActionGuide");
    expect(source).toContain("aria-label=\"出征行动指引\"");
    expect(source).toContain("actionGuide.primaryAction");
  });

  test("keeps the expedition flow as a mobile-friendly single-page command center", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("aria-label=\"远征行动台\"");
    expect(source).toContain("aria-label=\"本回合指挥摘要\"");
    expect(source).toContain("aria-label=\"当前可执行操作\"");
    expect(source).toContain("aria-label=\"最近行动结果\"");
    expect(source).toContain("journey-command-center");
    expect(source).toContain("journey-turn-summary");
    expect(source).toContain("journey-command-actions");
    expect(source).toContain("journey-action-deck");
    expect(source).toContain("commandActionItems");
    expect(source).toContain("currentActionQueue");
    expect(source).toContain("onClick={item.onSelect}");
    expect(source).toContain("aria-label=\"当前节点操作提示\"");
    expect(source).toContain("本节点动作已收拢到上方远征行动台。");
    expect(source).toContain("避免同一页出现两套可点击按钮。");
    expect(source).toContain("journey-command-result");
    expect(source).toContain("journeyActionPulse");
    expect(source).toContain("aria-label=\"出征行动脉冲\"");
    expect(source).toContain("行动反馈");
    expect(source).toContain("主要后果");
    expect(source).toContain("journeyActionResultBreakdown");
    expect(source).toContain("lastActionDelta");
    expect(source).toContain("annotateJourneyActionDelta");
    expect(source).toContain("buildJourneyActionDelta");
    expect(source).toContain("formatSignedResourceDelta");
    expect(source).toContain("aria-label=\"行动结果拆解\"");
    expect(source).toContain("资源变化");
    expect(source).toContain("队伍状态");
    expect(source).toContain("路线推进");
    expect(source).toContain("风险变化");
    expect(source).toContain("本次战利");
    expect(source).toContain("无变化");
    expect(source).toContain("当前阻碍");
    expect(source).toContain("推荐动作");
    expect(source).toContain("撤离收益");
    expect(source).toContain("aria-label=\"手机端当前行动面板\"");
    expect(source).toContain("本回合行动");
    expect(source).toContain("直接选择下一步");
    expect(source).toContain("每个选项都会推进旅途");
    expect(source).toContain("aria-label=\"手机端单页出征总控\"");
    expect(source).toContain("onePageCommandItems");
    expect(source).toContain("所有准备、行动和归队提示都在这一页完成。");
    expect(source).toContain("当前操作");
    expect(source).toContain("出发以后");
    expect(source).toContain("回基地");
    expect(source).toContain("journey-mobile-flow");
    expect(source).toContain("aria-label=\"手机端远征页内导航\"");
    expect(source).toContain("aria-label=\"手机端单页行动摘要\"");
    expect(source).toContain("mobilePrimaryActions");
    expect(source).toContain("aria-label=\"手机端当前行动\"");
    expect(source).toContain("journey-mobile-command-actions");
    expect(source).toContain("更多操作");
    expect(source).toContain("当前回合");
    expect(source).toContain("scrollToJourneySection");
    expect(source).toContain("id=\"journey-action-options\"");
    expect(source).toContain("id=\"journey-vitals\"");
    expect(source).toContain("id=\"journey-process\"");
    expect(source).toContain("id=\"journey-extraction\"");
    expect(source).toContain("aria-label=\"手机端出征路线摘要\"");
    expect(source).toContain("aria-label=\"当前路线步骤\"");
    expect(source).toContain("aria-label=\"关键状态\"");
    expect(source).toContain("journey-vitals-strip");
    expect(source).toContain("journey-detail-grid");
    expect(styles).toContain(".journey-command-center");
    expect(styles).toContain(".journey-turn-summary");
    expect(styles).toContain(".journey-command-actions");
    expect(styles).toContain(".journey-action-deck");
    expect(styles).toContain(".journey-action-queue-list");
    expect(styles).toContain(".journey-action-queue-list button");
    expect(styles).toContain(".journey-command-button strong b");
    expect(styles).toContain(".journey-node-command-note");
    expect(styles).toContain(".journey-primary-actions .combat-action-grid");
    expect(styles).toContain(".journey-command-result");
    expect(styles).toContain(".journey-action-pulse");
    expect(styles).toContain(".journey-action-pulse.danger");
    expect(styles).toContain(".journey-result-breakdown");
    expect(styles).toContain(".journey-result-breakdown article.warning");
    expect(styles).toContain(".expedition-one-page-command");
    expect(styles).toContain(".expedition-one-page-grid");
    expect(styles).toContain(".expedition-one-page-card");
    expect(styles).toContain(".journey-mobile-flow");
    expect(styles).toContain(".journey-mobile-route");
    expect(styles).toContain(".journey-mobile-meters");
    expect(styles).toContain(".journey-mobile-command-actions");
    expect(styles).toContain(".journey-mobile-command-links");
    expect(styles).toContain(".journey-section-nav");
    expect(styles).toContain(".journey-vitals-strip");
    expect(styles).toContain(".journey-primary-actions");
    expect(styles).toContain("position: sticky");
    expect(styles).toContain("padding-bottom: 28px");
    expect(styles).toContain(".journey-primary-actions .combat-action-grid");
    expect(styles).not.toContain("bottom: calc(76px + max(10px, env(safe-area-inset-bottom)))");
    expect(styles).toContain("@media (max-width: 720px)");
  });

  test("surfaces combat as a mobile-readable turn panel", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("aria-label=\"手机端回合战斗面板\"");
    expect(source).toContain("aria-label=\"战斗生命摘要\"");
    expect(source).toContain("combat-mobile-dashboard");
    expect(source).toContain("combatCommandBriefing");
    expect(source).toContain("aria-label=\"本回合战斗指挥\"");
    expect(source).toContain("战斗指挥");
    expect(source).toContain("执行：");
    expect(source).toContain("combat-command-briefing");
    expect(source).toContain("combat-command-grid");
    expect(source).toContain("combat-mobile-bars");
    expect(source).toContain("combat-mobile-intent");
    expect(source).toContain("combatLootPlan");
    expect(source).toContain("aria-label=\"战后处置建议\"");
    expect(source).toContain("combat-loot-plan");
    expect(source).toContain("处置建议");
    expect(source).toContain("combatRoundBreakdown");
    expect(source).toContain("aria-label=\"本回合战斗拆解\"");
    expect(source).toContain("我方动作");
    expect(source).toContain("敌人反应");
    expect(source).toContain("反制判定");
    expect(source).toContain("状态变化");
    expect(source).toContain("aria-label=\"战斗动作判读\"");
    expect(source).toContain("combatActionPreviews");
    expect(source).toContain("反制动作");
    expect(source).toContain("高风险动作");
    expect(source).toContain("常规选择");
    expect(source).toContain("latestCombatRound");
    expect(source).toContain("推荐反制");
    expect(styles).toContain(".combat-mobile-dashboard");
    expect(styles).toContain(".combat-command-briefing");
    expect(styles).toContain(".combat-command-grid");
    expect(styles).toContain(".combat-mobile-bars");
    expect(styles).toContain(".combat-mobile-intent");
    expect(styles).toContain(".combat-mobile-result");
    expect(styles).toContain(".combat-loot-plan");
    expect(styles).toContain(".combat-loot-plan-grid article.recommended");
    expect(styles).toContain(".combat-loot-plan-grid article.risky");
    expect(styles).toContain(".combat-round-breakdown");
    expect(styles).toContain(".combat-round-breakdown article.danger");
    expect(styles).toContain(".combat-action-readout");
  });

  test("keeps mobile navigation as an in-app bottom bar instead of page hops", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("data-app-mode=\"single-page\"");
    expect(source).toContain("onClick={() => setView(item.key)}");
    expect(source).toContain("mobilePrimary: true");
    expect(source).toContain("const navClassName = [");
    expect(source).toContain("item.mobilePrimary ? \"mobile-primary\" : \"mobile-secondary\"");
    expect(source).toContain("aria-label=\"手机端单页行动栏\"");
    expect(source).toContain("aria-label=\"数据库同步提示\"");
    expect(source).toContain("aria-label=\"房间捐入优先级\"");
    expect(source).toContain("可以继续本地试玩；重试会重新读取房间并上传当前进度。");
    expect(source).toContain("账号进度会先保留在本机；稍后刷新页面或重新登录后再同步。");
    expect(source).toContain("roomContributionPlan(session)");
    expect(source).toContain("捐入优先级");
    expect(source).toContain("mobile-command-strip");
    expect(source).toContain("sync-health-card");
    expect(source).not.toMatch(/<a\s+href=|window\.location\.href/);
    expect(styles).toContain(".mobile-command-strip");
    expect(styles).toContain(".nav-item.mobile-secondary");
    expect(styles).toContain(".sync-health-card");
    expect(styles).toContain(".room-contribution-plan");
    expect(styles).toContain(".room-contribution-grid");
    expect(styles).toContain("bottom: max(10px, env(safe-area-inset-bottom))");
    expect(styles).toContain("grid-auto-flow: column");
    expect(styles).toContain("overscroll-behavior-x: contain");
    expect(styles).toContain("padding-bottom: calc(76px + env(safe-area-inset-bottom))");
  });

  test("surfaces playtest language and release settings inside the single-page shell", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("const playtestSettings = {");
    expect(source).toContain("languagePackChecklist");
    expect(source).toContain("languageSwitchReadiness");
    expect(source).toContain("languageMode: \"中文\"");
    expect(source).toContain("英文包待接入后再开放切换");
    expect(source).toContain("aria-label=\"试玩设置\"");
    expect(source).toContain("aria-label=\"试玩环境状态\"");
    expect(source).toContain("aria-label=\"语言模式\"");
    expect(source).toContain("aria-label=\"语言切换准入\"");
    expect(source).toContain("aria-label=\"语言包覆盖范围\"");
    expect(source).toContain("playtestEnvironment.mode");
    expect(source).toContain("账号云端");
    expect(source).toContain("游客房间");
    expect(source).toContain("本地试玩");
    expect(source).toContain("房间人数");
    expect(source).toContain("中文已启用");
    expect(source).toContain("英文包待完整");
    expect(source).toContain("英文模式未解锁，避免半中文半英文进入试玩。");
    expect(source).toContain("混写拦截");
    expect(source).toContain("异常提示");
    expect(source).toContain("playtest-settings-card");
    expect(source).toContain("playtestSettings.pageStatus");
    expect(source).toContain("playtestSettings.releaseStatus");
    expect(styles).toContain(".playtest-settings-card");
    expect(styles).toContain(".playtest-environment-card");
    expect(styles).toContain(".playtest-settings-grid");
    expect(styles).toContain(".language-mode-switch");
    expect(styles).toContain(".language-switch-readiness");
    expect(styles).toContain(".language-switch-grid");
    expect(styles).toContain(".language-pack-grid");
  });

  test("keeps expedition actions reachable as a mobile single-page command dock", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("aria-label=\"当前可执行操作\"");
    expect(source).toContain("aria-label=\"当前行动栏说明\"");
    expect(source).toContain("aria-label=\"手机端当前行动面板\"");
    expect(source).toContain("aria-label=\"路线预告\"");
    expect(source).toContain("aria-label=\"手机端路线预告\"");
    expect(source).toContain("journey-command-actions");
    expect(source).toContain("journey-command-dock-heading");
    expect(source).toContain("journeyRouteIntel");
    expect(source).toContain("journey-route-intel");
    expect(source).toContain("journey-mobile-intel");
    expect(source).toContain("aria-label=\"出征后勤诊断\"");
    expect(source).toContain("supportDiagnosis.sources.map");
    expect(source).toContain("房间设施");
    expect(source).toContain("个人基地");
    expect(source).toContain("留守班次");
    expect(source).toContain("前方仍有战斗，优先保留弹药、医疗和队伍体力。");
    expect(source).toContain("outcome.supportText && <small className=\"facility-support-note\"");
    expect(source).toContain("formatSignedPercent(outcome.pressure)");
    expect(source).toContain("目标 +${outcome.objectiveBonus}");
    expect(styles).toContain(".journey-command-actions");
    expect(styles).toContain(".journey-action-deck");
    expect(styles).toContain(".journey-action-queue-list button");
    expect(styles).toContain(".journey-command-dock-heading");
    expect(styles).toContain(".journey-route-intel");
    expect(styles).toContain(".journey-mobile-intel");
    expect(styles).toContain(".support-diagnosis-card");
    expect(styles).toContain(".support-source-grid");
    expect(styles).toContain(".facility-support-note");
    expect(styles).toContain(".journey-command-actions {\n    display: none;");
    expect(styles).not.toContain("max-height: 42vh");
  });

  test("shows facility upgrade value as base and expedition impact", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("facilityImpactPreview");
    expect(source).toContain("baseDevelopmentRoute");
    expect(source).toContain("developmentRoute={baseDevelopmentRoute(session)}");
    expect(source).toContain("aria-label=\"设施升级收益预览\"");
    expect(source).toContain("aria-label=\"设施推荐原因\"");
    expect(source).toContain("aria-label=\"基地建设路线板\"");
    expect(source).toContain("建设路线");
    expect(source).toContain("aria-label=\"建设队列总览\"");
    expect(source).toContain("development-queue-board");
    expect(source).toContain("材料缺口");
    expect(source).toContain("队列完成");
    expect(source).toContain("development-project-why");
    expect(source).toContain("project.reason");
    expect(source).toContain("project.nextStep");
    expect(source).toContain("facility-impact-grid");
    expect(source).toContain("preview.baseText");
    expect(source).toContain("preview.expeditionText");
    expect(source).toContain("baseFeedback={baseFeedbackForScope(lastBaseActionFeedback, \"facilities\")}");
    expect(source).toContain("label=\"设施操作结果\"");
    expect(source).toContain("expeditionDoctrineForFacility");
    expect(source).toContain("aria-label=\"设施出征方针解锁\"");
    expect(source).toContain("facility-doctrine-unlock");
    expect(source).toContain("已解锁出征方针");
    expect(source).toContain("建造后解锁");
    expect(styles).toContain(".development-project-why");
    expect(styles).toContain(".development-route-board");
    expect(styles).toContain(".development-route-steps");
    expect(styles).toContain(".development-queue-board");
    expect(styles).toContain(".facility-impact-grid");
    expect(styles).toContain(".facility-doctrine-unlock");
  });

  test("shows a Chinese base task list on the overview", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("baseTaskList");
    expect(source).toContain("baseCommandBriefing");
    expect(source).toContain("baseCycleSteps");
    expect(source).toContain("aria-label=\"基地循环罗盘\"");
    expect(source).toContain("恢复");
    expect(source).toContain("建设");
    expect(source).toContain("出征");
    expect(source).toContain("复盘");
    expect(source).toContain("playtestRouteSteps");
    expect(source).toContain("aria-label=\"试玩路线导航\"");
    expect(source).toContain("试玩路线");
    expect(source).toContain("按这条路线走，可以体验完整基地到出征闭环。");
    expect(source).toContain("邀请好友、认领捐入和留守职责。");
    expect(source).toContain("aria-label=\"今日指挥板\"");
    expect(source).toContain("今日指挥板");
    expect(source).toContain("base-command-primary");
    expect(source).toContain("base-command-center");
    expect(source).toContain("base-command-actions");
    expect(source).toContain("lastBaseActionFeedback");
    expect(source).toContain("buildBaseActionFeedback");
    expect(source).toContain("baseDaySettlementPulse");
    expect(source).toContain("BaseActionFeedbackPanel");
    expect(source).toContain("baseFeedbackForScope");
    expect(source).toContain("aria-label={label}");
    expect(source).toContain("label=\"基地操作结果拆解\"");
    expect(source).toContain("最近操作");
    expect(source).toContain("资源变化");
    expect(source).toContain("幸存者状态");
    expect(source).toContain("baseExpeditionSupportBriefing");
    expect(source).toContain("aria-label=\"基地出征支援简报\"");
    expect(source).toContain("恢复线");
    expect(source).toContain("防线");
    expect(source).toContain("路线准备");
    expect(source).toContain("aria-label=\"基地归队承接\"");
    expect(source).toContain("overview-return-card");
    expect(source).toContain("latestReturnPlan.actions.map");
    expect(source).toContain("归队承接");
    expect(source).toContain("查看战报");
    expect(source).toContain("aria-label=\"今日基地待办\"");
    expect(source).toContain("aria-label=\"今日待办操作\"");
    expect(source).toContain("base-task-actions");
    expect(styles).toContain(".base-cycle-compass");
    expect(styles).toContain(".playtest-route-guide");
    expect(styles).toContain(".playtest-route-grid");
    expect(styles).toContain(".base-command-center");
    expect(styles).toContain(".base-command-primary");
    expect(styles).toContain(".base-command-actions");
    expect(styles).toContain(".base-action-feedback");
    expect(styles).toContain(".panel > .base-action-feedback");
    expect(styles).toContain(".base-action-feedback-grid");
    expect(styles).toContain(".base-action-feedback-grid article.warning");
    expect(styles).toContain(".base-settlement-pulse");
    expect(styles).toContain(".base-settlement-pulse-grid");
    expect(styles).toContain(".base-expedition-briefing");
    expect(styles).toContain(".base-expedition-briefing-grid");
    expect(styles).toContain(".overview-return-card");
    expect(styles).toContain(".overview-return-actions");
    expect(source).toContain("今日待办");
  });

  test("shows post-expedition recovery priority in the survivor view", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("recoveryPlan.immediateTreatments");
    expect(source).toContain("recoveryPlan.medicineAvailable");
    expect(source).toContain("recoveryPlan.medicineShortage");
    expect(source).toContain("recoveryPlan.nextAction");
    expect(source).toContain("baseFeedback={baseFeedbackForScope(lastBaseActionFeedback, \"survivors\")}");
    expect(source).toContain("label=\"幸存者操作结果\"");
    expect(source).toContain("recovery-next-action");
    expect(source).toContain("可治疗");
    expect(source).toContain("下一步");
    expect(styles).toContain(".recovery-next-action");
    expect(styles).toContain("repeat(auto-fit, minmax(120px, 1fr))");
  });

  test("shows Chinese next-step actions after expedition reports", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("aria-label=\"战报下一步\"");
    expect(source).toContain("aria-label=\"战后复盘\"");
    expect(source).toContain("aria-label=\"下一轮远征建议\"");
    expect(source).toContain("aria-label=\"幸存者成长路线\"");
    expect(source).toContain("aria-label=\"归队复盘脉冲\"");
    expect(source).toContain("summarizeFeedExpeditionDebrief");
    expect(source).toContain("summarizeFeedGrowthRoadmap");
    expect(source).toContain("summarizeFeedReturnPulse");
    expect(source).toContain("归队脉冲");
    expect(source).toContain("优先处理：");
    expect(source).toContain("report-expedition-debrief");
    expect(source).toContain("report-growth-roadmap");
    expect(source).toContain("report-return-pulse");
    expect(source).toContain("report-action-digest");
    expect(source).toContain("report-next-actions");
    expect(source).toContain("summarizeFeedBaseReturnPlan");
    expect(source).toContain("aria-label=\"远征回基地处理队列\"");
    expect(source).toContain("base-return-plan");
    expect(source).toContain("处理伤病");
    expect(source).toContain("准备下一次远征");
    expect(styles).toContain(".report-growth-roadmap");
    expect(styles).toContain(".report-expedition-debrief");
    expect(styles).toContain(".report-expedition-debrief-grid");
    expect(styles).toContain(".report-return-pulse");
    expect(styles).toContain(".report-return-pulse-grid");
    expect(styles).toContain(".report-action-digest");
    expect(styles).toContain(".report-next-actions");
    expect(styles).toContain(".base-return-plan");
  });

  test("shows a local playtest readiness checklist in the archive view", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("runPlayableLoopSmoke");
    expect(source).toContain("aria-label=\"试玩完整性检查\"");
    expect(source).toContain("核心试玩闭环已通过");
    expect(source).toContain("playtest-readiness-card");
    expect(source).toContain("playtest-checkpoint-grid");
    expect(source).toContain("aria-label=\"发布前本地门禁\"");
    expect(source).toContain("aria-label=\"发布准入检查\"");
    expect(source).toContain("releaseReadinessSteps");
    expect(source).toContain("默认不要频繁发布");
    expect(source).toContain("不要用线上部署当测试工具");
    expect(source).toContain("browserSmokeChecklist");
    expect(source).toContain("releaseBatchPolicy");
    expect(source).toContain("aria-label=\"发布批次判定\"");
    expect(source).toContain("先本地累积，形成完整试玩切片后再发布。");
    expect(source).toContain("局部小改");
    expect(source).toContain("aria-label=\"浏览器冒烟清单\"");
    expect(source).toContain("本地先走完整路径，线上只做验收。");
    expect(source).toContain("http://localhost:5173/?room=playtest-smoke");
    expect(source).toContain("https://ember-dossier.pages.dev/?room=playtest-smoke");
    expect(source).toContain("npm run release:preflight");
    expect(source).toContain("npm run release:verify");
    expect(source).toContain("npm run copy:check");
    expect(source).toContain("npm run playable:check");
    expect(source).toContain("npm run iteration:check");
    expect(source).toContain("playtestCheckpointLabel");
    expect(source).toContain("设施升级");
    expect(source).toContain("伤病治疗");
    expect(source).toContain("多人协作");
    expect(source).toContain("回合战斗");
    expect(source).toContain("回基地行动");
    expect(styles).toContain(".playtest-readiness-card");
    expect(styles).toContain(".playtest-checkpoint-grid");
    expect(styles).toContain(".playtest-checkpoint");
    expect(styles).toContain(".playtest-gate-strip");
    expect(styles).toContain(".release-readiness-card");
    expect(styles).toContain(".release-readiness-grid");
    expect(styles).toContain(".release-batch-card");
    expect(styles).toContain(".release-batch-grid");
    expect(styles).toContain(".browser-smoke-card");
    expect(styles).toContain(".browser-smoke-grid");
  });

  test("shows a Chinese room cooperation summary for multiplayer rooms", () => {
    const source = readFileSync("src/App.tsx", "utf8");
    const styles = readFileSync("src/styles.css", "utf8");

    expect(source).toContain("roomCooperationSummary");
    expect(source).toContain("roomCooperationPulse");
    expect(source).toContain("roomLaunchBriefing");
    expect(source).toContain("launchBriefing={roomLaunchBriefing(session)}");
    expect(source).toContain("pulse={roomCooperationPulse(session)}");
    expect(source).toContain("roomPlaytestReadiness");
    expect(source).toContain("aria-label=\"房间协作总览\"");
    expect(source).toContain("aria-label=\"房间行动链\"");
    expect(source).toContain("roomActionLadder");
    expect(source).toContain("roomReadinessItemTargetView");
    expect(source).toContain("aria-label=\"账号房间边界\"");
    expect(source).toContain("ownershipBoundaries");
    expect(source).toContain("账号保留");
    expect(source).toContain("房间共享");
    expect(source).toContain("单次远征");
    expect(source).toContain("aria-label=\"多人试玩开局检查\"");
    expect(source).toContain("aria-label=\"房间协作分工板\"");
    expect(source).toContain("aria-label=\"多人开局指挥\"");
    expect(source).toContain("多人开局指挥");
    expect(source).toContain("room-launch-briefing");
    expect(source).toContain("room-launch-grid");
    expect(source).toContain("按顺序补齐邀请、捐入、编队、班次和出征");
    expect(source).toContain("协作状态");
    expect(source).toContain("下一步：");
    expect(source).toContain("summary.actionHint");
    expect(source).toContain("cooperationLanes.map");
    expect(source).toContain("捐入补给");
    expect(source).toContain("出征编队");
    expect(source).toContain("留守班次");
    expect(source).toContain("等待认领");
    expect(source).toContain("playtestReadiness.items.map");
    expect(source).toContain("roomReadinessTargetView(playtestReadiness)");
    expect(source).toContain("开局检查");
    expect(source).toContain("summary.gaps.map");
    expect(source).toContain("aria-label=\"房间协作缺口\"");
    expect(source).toContain("room-cooperation-board");
    expect(source).toContain("room-cooperation-pulse");
    expect(source).toContain("aria-label=\"好友房间协作脉冲\"");
    expect(source).toContain("协作脉冲");
    expect(source).toContain("room-cooperation-metrics");
    expect(source).toContain("room-cooperation-gaps");
    expect(source).toContain("room-gap-card");
    expect(source).toContain("room-playtest-readiness");
    expect(source).toContain("room-playtest-check-grid");
    expect(source).toContain("member.collaborationHint");
    expect(source).toContain("member-collaboration-hint");
    expect(source).toContain("协作建议：");
    expect(styles).toContain(".room-cooperation-board");
    expect(styles).toContain(".room-launch-briefing");
    expect(styles).toContain(".room-launch-grid");
    expect(styles).toContain(".room-cooperation-pulse");
    expect(styles).toContain(".room-cooperation-pulse-grid");
    expect(styles).toContain(".room-action-ladder");
    expect(styles).toContain(".room-action-ladder-grid");
    expect(styles).toContain(".ownership-boundary-card");
    expect(styles).toContain(".ownership-boundary-grid");
    expect(styles).toContain(".room-cooperation-metrics");
    expect(styles).toContain(".room-cooperation-gaps");
    expect(styles).toContain(".room-duty-board");
    expect(styles).toContain(".room-gap-card");
    expect(styles).toContain(".room-playtest-readiness");
    expect(styles).toContain(".room-playtest-check-grid");
    expect(styles).toContain(".member-collaboration-hint");
  });
});
